// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TCd8sTaCPjCwvEIS1GnakDpXDzPFOuU',
    appId: '1:179320462747:web:542d064b9c9a4204a1953e',
    messagingSenderId: '179320462747',
    projectId: 'thesis-sangkaestay',
    authDomain: 'thesis-sangkaestay.firebaseapp.com',
    storageBucket: 'thesis-sangkaestay.firebasestorage.app',
    measurementId: 'G-H98L8W0EPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOnU5ZDJJKOWiONYRQEeO8zWSZI3l6gYM',
    appId: '1:179320462747:android:aa5e1aef21521c92a1953e',
    messagingSenderId: '179320462747',
    projectId: 'thesis-sangkaestay',
    storageBucket: 'thesis-sangkaestay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCupOoP4-paSZMCRp3bxZXLv-oCnqN1Foo',
    appId: '1:179320462747:ios:5c3fb43fe93f251ba1953e',
    messagingSenderId: '179320462747',
    projectId: 'thesis-sangkaestay',
    storageBucket: 'thesis-sangkaestay.firebasestorage.app',
    iosClientId: '179320462747-4u0jqqap17a4tnuj2gmiq4463osgp7ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.sankaestay',
  );
}
